<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXE2qRtD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXE2qRtD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXE2qRtD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXE2qRtD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXE2qRtD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XE2qRtD',
    'container.build_id' => 'e1636079',
    'container.build_time' => 1568896112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXE2qRtD');
