<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9zLP1Pt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9zLP1Pt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9zLP1Pt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9zLP1Pt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9zLP1Pt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9zLP1Pt',
    'container.build_id' => '7d6fd69f',
    'container.build_time' => 1567163447,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9zLP1Pt');
