<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZx8IH6c\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZx8IH6c/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZx8IH6c.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZx8IH6c\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZx8IH6c\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Zx8IH6c',
    'container.build_id' => '48f123b6',
    'container.build_time' => 1567018046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZx8IH6c');
